### ISSUE TITLE
Would you consider contributing to NWebSec?

### ISSUE THREAD

**Issue by RehanSaeed** [tpeczek/Lib.AspNetCore.Security#12]
I've been using [NWebSec](https://github.com/NWebsec/NWebsec) for some time for security related HTTP headers etc. as it's pretty comprehensive and popular. Both NWebSec and your library have a fair amount of overlap while still having some features missing in both. Would you consider contributing to NWebSec to produce a one-stop shop for all your ASP.NET Core security needs? In particular I'm thinking about:

- [CSP Hash TagHelper](https://github.com/NWebsec/NWebsec/issues/100)
- [Expect-CT HTTP Header](https://github.com/NWebsec/NWebsec/issues/99)

**Comment by tpeczek** [comment]
So I did a little bit of thinking on that. This "library" is a place for me to play with the security stuff I want in a way I want. If anything interesting (in my opinion) comes out of it I blog about it. This is my contribution for everybody and certainly more than enough to implement similar futures in different libraries, while I keep playing and experimenting here. If somebody decides to use this library it will be great. If this library will trigger other libraries to have new features it will be also great. If this will have no traction at all, it will be ok. I believe variety is a good thing and at this point I'll put my effort here where I have full freedom and still a couple of ideas.

**Comment by RehanSaeed** [comment]
Totally understandable. I myself do the same thing with the projects I run. You'r blog posts are different from the usual 'getting started with x' and thus very interesting. Keep up the good work.
